### ISSUE TITLE
How big can a message be?

### ISSUE THREAD

**Issue by johnnymatthews** [entropyxyz/entropy-docs#112]
How much stuff can I put into a message?

**Comment by ameba23** [comment]
Assuming you mean the message in a signature request. i think it is as much as axum (the http server) will allow in a post request, which by default is 2mb.  Since messages are encoded as hex they take up twice as much space, plus there is some other data in the request, so lets say just under 1mb.  There might also be restrictions from the http client, so it depends where the request is coming from.
